baseURL: "https://gautammanohar.com"
languageCode: "en-us"
title: "Gautam Manohar"
theme: "gautam-manohar"
MetaDataFormat: "yaml"
pygmentsCodeFences: true
pygmentsUseClasses: true
disqusShortName: gautam-2
params:
  author: "Gautam Manohar"
  googleAnalytics: UA-115904815-1
  eulerMax: 100
permalinks:
  math: /:title/